### ISSUE TITLE
Allowing custom request object.

### ISSUE THREAD

**Issue by curtisturner** [IonicaBizau/cheerio-req#3]
Allowing for usage of custom req objects will enable users to sub in the full featured: https://github.com/request/request or another request library of their choosing. The fork I created just uses request instead of tinyreq and that allowed for easy cookie jar. 

As an enhancement I'm suggesting allow custom request objects to be plugged in or switching from tinyreq to request.

Thanks for this library and the scrape-it library. Very useful.

**Comment by IonicaBizau** [comment]
That would be cute! ✨ 

Maybe passing an object like this:

``` js
{
  url: "...",
  request: require("request")
}
```

And then the `request` field will be deleted once we get it, and then we pass the object to the request method. 👍

**Comment by IonicaBizau** [comment]
Now you should be able to do:

``` js
const _request = require("request")
    , request = require("cheerio-req")
    ;

request.request = (options, cb) => {
    _request(options, (err, res, body) => cb(err, body, res));
};
```
