### ISSUE TITLE
this module is trying to connect to my local host getting : ECONNREFUSED

### ISSUE THREAD

**Issue by gpapin** [IonicaBizau/cheerio-req#5]
Let's say I have this bit of code:

``` js
const cheerioReq = require("cheerio-req");

cheerioReq("http://google.co.uk", (err, $) => {
     console.log(err);
});
```

This will give me this output:

``` js
{ Error: connect ECONNREFUSED 127.0.0.1:443
    at Object.exports._errnoException (util.js:953:11)
    at exports._exceptionWithHostPort (util.js:976:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 443 }
```

I've already done a traceroute, it's getting the right path, I've also done a wget and everything if fine so I have no idea what's going on. I should also note that it used to work last week and I didn't touched my code since...

**Comment by IonicaBizau** [comment]
It should be fixed already. `npm update` should fix your issue, if not `rm -rf node_modules && npm i`.

**Comment by IonicaBizau** [comment]
@gpapin Can you confirm it's fixed?

**Comment by gpapin** [comment]
I confirm it's fixed ! Thanks @IonicaBizau :)
